services:
  manager:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bott_manager
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
      - app_data:/var/www/html/public/uploads
    networks:
      - mynetwork
    depends_on:
      - bott_postgres
      - bott_redis

  waha:
    image: devlikeapro/waha
    container_name: waha_app
    restart: always
    ports:
      - "3001:3001"
    stdin_open: true  # Habilita interação com o terminal (equivalente a -it)
    tty: true  # Habilita o terminal para o contêiner
    volumes:
      - ./waha_data:/app
    networks:
      - mynetwork
    env_file:
      - .env

  bott_redis:
    image: redis:latest
    container_name: bott_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - mynetwork

  bott_postgres:
    image: postgres:latest
    container_name: bott_postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
    networks:
      - mynetwork
    env_file:
      - .env

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: always
    ports:
      - "${SERVER_EXTERNAL_PORT_N8N_APP}:${N8N_PORT}"
    volumes:
      - ./n8n_data:/home/node/.n8n
    networks:
      - mynetwork
    env_file:
      - .env
    depends_on:
      - bott_postgres
      - bott_redis

  n8n_workers:
    image: n8nio/n8n:latest
    container_name: n8n_workers
    restart: always
    ports:
      - "${SERVER_EXTERNAL_PORT_N8N_WORKERS}:${N8N_PORT}"
    volumes:
      - ./n8n_data:/home/node/.n8n
    networks:
      - mynetwork
    env_file:
      - .env
    depends_on:
      - bott_postgres
      - bott_redis
    command: worker

  n8n_webhooks:
    image: n8nio/n8n:latest
    container_name: n8n_webhooks
    restart: always
    ports:
      - "${SERVER_EXTERNAL_PORT_N8N_WEBHOOKS}:${N8N_PORT}"
    volumes:
      - ./n8n_data:/home/node/.n8n
    networks:
      - mynetwork
    env_file:
      - .env
    depends_on:
      - bott_postgres
      - bott_redis
    command: webhook

volumes:
  app_data:
  waha_data:

networks:
  mynetwork:
    driver: bridge
